apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: fogproject
spec:
  replicas: 1
  template:
    metadata:
      name: fogproject
      labels:
        app: fogproject
    spec:
      hostNetwork: true
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - nodenuvem5
      containers:
        - name: fogproject
          image: deschamps001/fogproject:kubernetes
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
          volumeMounts:
            - name: mysql
              mountPath: /var/lib/mysql
      restartPolicy: Always
      volumes:
        - name: mysql
          persistentVolumeClaim:
            claimName: fogproject-mysql