kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: dimensionamento
  namespace: producao
spec:
  tls:
    - hosts:
        - dimensionamento.sj.ifsc.edu.br
      secretName: tls-ifsc-sje-wildcard
  rules:
    - host: dimensionamento.sj.ifsc.edu.br
      http:
        paths:
          - path: /
            backend:
              serviceName: dimensionamento
              servicePort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: dimensionamento
  namespace: producao
  labels:
    app: dimensionamento
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: dimensionamento

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dimensionamento
  namespace: producao
  labels:
    app: dimensionamento
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: dimensionamento
    spec:      
      containers:
      - name: dimensionamento
        image: cticsjeifsc/dimensionamento
        env:
          - name: TZ
            value: "America/Recife"
        ports:
        - name: http
          containerPort: 80
        livenessProbe:
          httpGet:
            path: /index.html
            port: 80
            scheme: HTTP
          initialDelaySeconds: 60
          timeoutSeconds: 10
          failureThreshold: 6        
        resources:
          limits:
            memory: 256Mi
            cpu: 1
          requests:
            memory: 32Mi
            cpu: 300m
