apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: mosquitto
    protocol: mqtt
  name: mosquitto-mosquitto-conf
  namespace: ensino
data:
  mosquitto.conf: |-
    persistence true
    persistence_location /mosquitto/data/
    autosave_interval 60
    log_dest stdout
    listener 1883
    listener 9001
    protocol websockets

---

apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: mosquitto
    protocol: mqtt
  name: mosquitto-mosquitto-data
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  storageClassName: mosquitto-mosquitto-data
  cephfs:
      monitors:
      - 10.10.10.1:6789
      - 10.10.10.5:6789
      - 10.10.10.6:6789
      path: /kubernetes/ifsc/sje/srv/mosquitto/data
      user: admin
      secretRef:
        name: ceph-secret

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  labels:
    app: mosquitto
    protocol: mqtt
  name: mosquitto-mosquitto-data
  namespace: ensino
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  storageClassName: mosquitto-mosquitto-data

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    app: mosquitto
    protocol: mqtt
  name: mosquitto
  namespace: ensino
spec:
  rules:
    - host: mqtt.sj.ifsc.edu.br
      http:
        paths:
          - backend:
              serviceName: mosquitto-ws
              servicePort: 9001
            path: /
  tls:
    - hosts:
        - mqtt.sj.ifsc.edu.br
      secretName: tls-ifsc-sje-wildcard

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: mosquitto
    protocol: mqtt
  name: mosquitto-mqtt
  namespace: ensino
spec:
  externalIPs:
    - "191.36.8.1"
    - "191.36.8.4"
    - "191.36.8.6"
    - "191.36.8.7"
    - "191.36.8.25"
  ports:
    - name: mqtt
      port: 1883
      protocol: TCP
      targetPort: 1883
  selector:
    app: mosquitto
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: mosquitto
    protocol: mqtt
  name: mosquitto-ws
  namespace: ensino
spec:
  ports:
    - name: mqtt-ws
      port: 9001
      protocol: TCP
      targetPort: 9001
  selector:
    app: mosquitto

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: mosquitto
    protocol: mqtt
  name: mosquitto
  namespace: ensino
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mosquitto
        protocol: mqtt
    spec:
      containers:
        - image: docker.io/cticsjeifsc/mosquitto:latest
          name: mosquitto
          ports:
            - containerPort: 1883
            - containerPort: 9001
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 2
              memory: 512Mi
          volumeMounts:
            - name: mosquitto-mosquitto-conf
              mountPath: /mosquitto/config/
            - name: mosquitto-mosquitto-data
              mountPath: /mosquitto/data/
      restartPolicy: Always
      volumes:
      - name: mosquitto-mosquitto-conf
        configMap:
          name: mosquitto-mosquitto-conf
          items:
          - path: "mosquitto.conf"
            key: mosquitto.conf
      - name: mosquitto-mosquitto-data
        persistentVolumeClaim:
          claimName: mosquitto-mosquitto-data

