apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: mosquitto
    protocol: mqtt
  name: mosquitto-mosquitto-data
  namespace: producao
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: storage1
    path: /mnt/storage/storage/kubernetes/ifsc/sje/a/saas/srv/mosquitto/mosquitto/data
