apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-bareos-sd-data
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5000Gi
  iscsi:
    chapAuthDiscovery: true
    chapAuthSession: true
    fsType: ext4
    initiatorName: "iqn.2019-11.pv-bareos-sje:00:2955d7e72762"
    iqn: "iqn.1992-04.com.emc:cx.ckm00123700157.a5"
    iscsiInterface: default
    lun: 0
    readOnly: false
    secretRef:
      name: chap-secret-pv-bareos-sd-sje
    targetPortal: "172.18.31.2:3260"
  storageClassName: pv-bareos-sd-data

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-bareos-sd-etc
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  cephfs:
    monitors:
      - "10.10.10.1:6789"
      - "10.10.10.5:6789"
      - "10.10.10.6:6789"
    path: /kubernetes/ifsc/sje/srv/bareos/config/storage
    secretRef:
      name: ceph-secret
    user: admin
  storageClassName: pv-bareos-sd-etc

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: pv-bareos-sd-data
  name: pv-bareos-sd-data
  namespace: producao
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: pv-bareos-sd-data

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: pv-bareos-sd-etc
  name: pv-bareos-sd-etc
  namespace: producao
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: pv-bareos-sd-etc

---
apiVersion: v1
kind: Service
metadata:
  name: bareos-sd
  namespace: producao
spec:
  ports:
    - name: bareos-sd
      port: 9103
      protocol: TCP
      targetPort: 9103
  selector:
    app: bareos-sd

---
apiVersion: v1
kind: Service
metadata:
  name: bareos-sd-externo
  namespace: producao
spec:
  externalIPs:
    - "191.36.8.1"
    - "191.36.8.4"
    - "191.36.8.6"
    - "191.36.8.7"
    - "191.36.8.25"
  ports:
    - name: bareos-sd
      port: 9103
      protocol: TCP
      targetPort: 9103
  selector:
    app: bareos-sd

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bareos-sd
  name: bareos-sd
  namespace: producao
spec:
  selector:
    matchLabels:
      app: bareos-sd
  template:
    metadata:
      labels:
        app: bareos-sd
    spec:
      containers:
        - env:
            - name: BAREOS_SD_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: bareos-sd-password
                  name: bareos-sd-password
            - name: TZ
              value: America/Recife
          image: "barcus/bareos-storage:19-ubuntu"
          name: bareos-sd
          ports:
            - containerPort: 9103
              name: bareos
          resources:
            limits:
              cpu: 2
              memory: 1Gi
            requests:
              cpu: 180m
              memory: 128Mi
          volumeMounts:
            - mountPath: /var/lib/bareos/storage
              name: pv-bareos-sd-data
            - mountPath: /etc/bareos
              name: pv-bareos-sd-etc
      volumes:
        - name: bareos-sd-password
          secret:
            secretName: bareos-sd-password
        - name: pv-bareos-sd-data
          persistentVolumeClaim:
            claimName: pv-bareos-sd-data
        - name: pv-bareos-sd-etc
          persistentVolumeClaim:
            claimName: pv-bareos-sd-etc
