apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: isc-dhcp
  name: isc-dhcp
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 100Mi
  cephfs:
    monitors:
      - "10.10.10.1:6789"
      - "10.10.10.5:6789"
      - "10.10.10.6:6789"
    path: /kubernetes/ifsc/sje/srv/isc-dhcp
    secretRef:
      name: ceph-secret
    user: admin
  storageClassName: isc-dhcp

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: isc-dhcp
  name: isc-dhcp
  namespace: producao
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: isc-dhcp

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: isc-dhcp
  name: isc-dhcp
  namespace: producao
spec:
  selector:
    matchLabels:
      app: isc-dhcp
  template:
    metadata:
      labels:
        app: isc-dhcp
      name: isc-dhcp
    spec:
      containers:
        - args: ["/usr/sbin/dhcpd", "-4", "-d", "-cf", "/var/lib/dhcp/dhcpd.conf"]
          image: "cticsjeifsc/isc-dhcp:latest"
          name: isc-dhcp
          ports:
            - containerPort: 67
              protocol: UDP
            - containerPort: 67
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 125m
              memory: 32Mi
          volumeMounts:
            - mountPath: /var/lib/dhcp
              name: isc-dhcp
      hostNetwork: true
      nodeName: vmnuvem1
      volumes:
        - name: isc-dhcp
          persistentVolumeClaim:
            claimName: isc-dhcp
