apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: bareos-sd-continente
  labels:
    app: bareos-sd-continente
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: bareos-sd-continente
    spec:
      containers:
      - name: bareos-sd-continente
        image: barcus/bareos-storage:latest
        env:
          - name: BAREOS_SD_PASSWORD
            valueFrom:
              secretKeyRef:
                name: bareos-sd-password
                key: bareos-sd-password
          - name: TZ
            value: "America/Sao_Paulo"
        ports:
        - name: bareos
          containerPort: 9103
        resources:
          requests:
            cpu: 1
            memory: 1Gi
          limits:
            cpu: 2
            memory: 2Gi
        volumeMounts:
        - name: pv-bareos-sd-continente-bkp
          mountPath: /var/lib/bareos/storage
        - name: pv-bareos-sd-continente-conf
          mountPath: /etc/bareos
      volumes:
      - name: bareos-sd-password
        secret:
          secretName: bareos-sd-password
      - name: pv-bareos-sd-continente-bkp
        persistentVolumeClaim:
          claimName: pv-bareos-sd-continente-bkp
      - name: pv-bareos-sd-continente-conf
        persistentVolumeClaim:
          claimName: pv-bareos-sd-continente-conf

