kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: netbox-postgresql-base
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: netbox-postgresql
