apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: samba
    dir: lib
  name: samba-lib
  namespace: testes
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  storageClassName: samba-lib
  mountOptions:
    - nolock
  nfs:
    server: storage1
    path: /mnt/storage/storage/kubernetes/ifsc/sje/a/saas/srv/samba/lib

---

apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: samba
    dir: log
  name: samba-log
  namespace: testes
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: samba-log
  mountOptions:
    - nolock
  nfs:
    server: storage1
    path: /mnt/storage/storage/kubernetes/ifsc/sje/a/saas/srv/samba/log

---

apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: samba
    dir: dados
  name: samba-home
  namespace: testes
spec:
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteMany
  storageClassName: samba-home
  mountOptions:
    - nolock
  nfs:
    server: storage1
    path: /mnt/storage/storage/kubernetes/ifsc/sje/a/saas/srv/samba/dados/home

---

apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: samba
    dir: dados
  name: samba-grupos
  namespace: testes
spec:
  capacity:
    storage: 300Gi
  accessModes:
    - ReadWriteMany
  storageClassName: samba-grupos
  mountOptions:
    - nolock
  nfs:
    server: storage1
    path: /mnt/storage/storage/kubernetes/ifsc/sje/a/saas/srv/samba/dados/grupos
