all: delete create

delete:
#	kubectl delete -f Ingress.yaml
#	kubectl delete -f Service.yaml
	kubectl delete -f Deployment.yaml

create:
	kubectl create -f Deployment.yaml
#	kubectl create -f Service.yaml
#	kubectl create -f Ingress.yaml
