apiVersion: v1
kind: PersistentVolume
metadata:
  name: sharelatex-mongo-base
spec:
  capacity:
    storage: 5022Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: storage1
    path: /mnt/storage/storage/kubernetes/ifsc/sje/a/saas/srv/sharelatex/mongo

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: sharelatex-redis-base
spec:
  capacity:
    storage: 8520Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: storage1
    path: /mnt/storage/storage/kubernetes/ifsc/sje/a/saas/srv/sharelatex/redis

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: sharelatex-sharelatex-arquivos
spec:
  capacity:
    storage: 10018Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: storage1
    path: /mnt/storage/storage/kubernetes/ifsc/sje/a/saas/srv/sharelatex/sharelatex
